export const Title_Url={
    "visitPageTitle" : "GUVI | Learn to code in your native language",
    "visitPageUrl" : "https://www.guvi.in/",
    "FaQTitle" :'FAQ | GUVI',
    "FaQUrl" : 'https://www.guvi.in/faq/',
    "CodeKataTitle" : "CodeKata | GUVI",
    "CodeKataUrl" : "https://www.guvi.in/code-kata/",
    "WebkataTitle" : "Webkata | GUVI",
    "WebKataUrl" : "https://www.guvi.in/webkata/",
    "DebuggingTitle" : "Debugging | GUVI",
    "DebuggingUrl" : "https://www.guvi.in/debugging/",
    "IDETitle" : "IDE | GUVI",
    "IDEUrl" : "https://www.guvi.in/ide/",
    "LeaderBoardTitle" : "Leader Board | GUVI",
    "LeaderBoardUrl" : "https://www.guvi.in/leader-board/",
    "RewardsTitle" : "Rewards | GUVI",
    "RewardsUrl" : "https://www.guvi.in/rewards/",
    "ReferralTitle" : "Referral | GUVI",
    "ReferralUrl" : "https://www.guvi.in/referral/",
    "forumTitle" : "GUVI - Learn Practice Get Hired",
    "forumUrl": "https://forum.guvi.in/",
    "ProgrammingLanguagesTitle" : "Best Programming Languages Courses with Certification in 2023",
    "ProgrammingLanguagesUrl" : 'https://www.guvi.in/courses/programming/',
    "DataScienceTitle" : "Best Data Science Courses Online with Certification in 2023 | GUVI",
    "DataScienceUrl" : 'https://www.guvi.in/courses/data-science/',
    "WebDevelopmentTitle" : "Best Web Development Courses Online with Certification in 2023",
    "WebDevelopmentUrl" : 'https://www.guvi.in/courses/web-development/',
    "DataBaseandcloudcomputingTitle" : "Best Database & Cloud Computing Courses with Certification",
    "DataBaseandcloudcomputingUrl" : 'https://www.guvi.in/courses/database-and-cloud-computing/',
    "SoftwareTesting_AutomationTitle" : "Best Software Testing & Automation Courses with Certification",
    "SoftwareTesting_AutomationUrl" : 'https://www.guvi.in/courses/software-testing-and-automation/',
    "ITandSoftwareTitle" : "Best IT and Software Courses Online with Certification in 2023",
    "ITandSoftwareUrl" : 'https://www.guvi.in/courses/it-and-software/',
    "NetworkandSecurityTitle" : "Best Network & Security Courses with Certification In 2023 | GUVI",
    "NetworkandSecurityUrl" : 'https://www.guvi.in/courses/network-and-security/',
    "Web3Title": "Best Web 3.0 Courses Online with Certification In 2023 | GUVI",
    "Web3Url" : 'https://www.guvi.in/courses/web-3-0/',
    "MobileDevelopmentTitle" : "Best Mobile Development Courses with Certification in 2023 | GUVI",
    "MobileDevelopmentUrl" : 'https://www.guvi.in/courses/mobile-development/',
    "UI_UXTitle" : "Best UI/UX Courses Online with Certification In 2023 | GUVI",
    "UI_UXUrl" : 'https://www.guvi.in/courses/ui-ux-design/',
    "DigitalMarketingTitle" : "Best Digital Marketing Courses with Certification in 2023 | GUVI",
    "DigitalMarketingUrl" : 'https://www.guvi.in/courses/digital-marketing/',
    "commonTitle" : "Online Courses Category | GUVI",
    "premiumLibraryUrl" : 'https://www.guvi.in/category/?library=premiumLibrary',
    "AtomicLibraryUrl" : 'https://www.guvi.in/category/?library=atomicLibrary',
    "EssentialLibraryUrl" : 'https://www.guvi.in/category/?library=essentialLibrary',
    "FreeLibraryUrl" : 'https://www.guvi.in/category/?library=freeLibrary',
    "AllCoursesUrl" : 'https://www.guvi.in/category/',
    "ProfileTitle" : "Profile | GUVI",
    "ProfileUrl" : "https://www.guvi.in/deepusgj47401"



}