export const home={
    "subscribe" : "#subscribeNowButton",
    "gender" :  "#gender",
    "country" : "#country-selectized",
    "state" : "#state-selectized",
    "city" : "#city-selectized",
    "continue" :  "#continue-btn",
    "degree" : "#degree",
    "department" : "#department",
    "profile" : "#currentProfile",
    "company" : "#company",
    "role" : "#role",
    "location" : "#location",
    "experience" : "#experience",
    "skills" : "#skills-selectized",
    "codingProfile" : "#codingProfile",
    "reference" : "#refernce",
    "Interest" : "#interestedArea-selectized",
    "popup" : "[class='modal-content card-mod']",
    "GuviLogo" : ".navbar-brand",
    "FaQ" : "[href='/faq/']",
    "GeekPoints" : ".experience",
    "Rank" : ".rank",
    "FaQMessage" : ".cp-title",
    "ProfileAvatar" : ".gravatar-wrap",
    "CourseBanner" : "#CourseBannerView",
    "GuviLogo2" : "[alt='logo']",
    "CourseDetails" : "[class='iE sD']",
    "CourseNav" : ".icons-courses",
    "CourseTitle" : ".mr-auto",
    "Codekata" : ".icons-code-kata",
    "codekataPageText" : ".page-header",
    "webkata" : ".icons-Webkata",
    "webkataPageText" : ".page-header > .row",
    "Debugging" : ".icons-debugging",
    "DeubggingPageText" : ".page-header > .row",
    "IdePopUp" : "#tryButton",
    "Ide" : ".icons-ide",
    "editor" : "#editor",
    "LeaderBoard" : ".icons-leader-board",
    "Rewards" : ".icons-rewards",
    "RewardsPageText" : ".mb-3",
    "Referral" : ".icons-Referral",
    "ReferralpageText" : ".referal-heading-2",
    "Forum" : ".icons-forum",
    "AtomicLibraryMessage" : "[class='d-none d-md-block']",
    "AtomicLibraryParent" : "#atomicLib",
    "AtomicCourses" : "[class='course-tag atomic']",
    "AtomicFreeCourse" : ".freeCourseCustom",
    "EssentialLibraryParent" : "#essentialLib",
    "EssentialCourses" : "[class='course-tag essential']",
    "EssentialFreeCourse" : ".freeCourseCustom",
    "EssentialFreeCertificate" : ".free-certificate",
    "Categories": "#cardCategories",
    "CategoryType" : "[class='col-sm-3 col-6']",
    "premiumLibraryParent" : "#premiumLib",
    "PremiumCourse" : "[class='course-tag premium']",
    "CourseLanguageParent" : "#languageCardSection",
    "courseLanguage" : "[class='col-sm-2 col-6 pt-sm-0 pt-2']",
    "FreeLibrary" : "#contact-tab",
    "FreeLibraryParent" : "#freeLib",
    "FreeCourses" : "[class='course-tag free']",
    "AtomicEntireTag" : "[class='col-lg-3 col-md-4 col-xs-12 p-2']",
    "VideoPlayerParent" : "#courses-video-page",
    "VideoPlayer" : "[class='embed-responsive embed-responsive-21by9 video-div video-wrap']",
    "sortby" : "[class='dropdown mr-2']",
    "popularity" : "[data-id='enrolled_0']",
    "EnrolledCount" : "[class='d-inline']",
    "search" : "[placeholder='Search']",
    "AtomicLibraryGrandParent" : "#course-list-atomic",
    "AtomicCourseBox" : "[class='col-lg-3 col-md-4 col-xs-12 p-2']",
    "AtomicCourseText" : "[class='font-weight-bold course-title mb-1']",
    "EssentialLibraryGrandParent" : "#course-list",
    "EssentialCourseBox" : "[class='col-lg-3 col-md-4 col-xs-12 p-2']",
    "EssentialParent" : "#essentialLib",
    "EssentialCourseText" : "[class='font-weight-bold course-title mb-1']",
    "PremiumLibraryGrandParent" : "#course-list-premium",
    "PremiumCourseBox" : "[class='col-lg-3 col-md-4 col-xs-12 p-2']",
    "PremiumParent" : "#premiumLib",
    "premiumCourseText" : "[class='font-weight-bold course-title mb-1']",
    "Explore" : "[class='list-group list-group-horizontal-md mr-3']",
    "ProgrammingLanguage" : "#courseExploreDropdown > [href='/courses/programming/'] > .categoryText",
    "CategoryTitle" : "[class='col-sm-12 col-md-11 pt-2']",
    "DataScience" : "#courseExploreDropdown > [href='/courses/data-science/'] > .categoryText",
    "WebDevelopment" : "#courseExploreDropdown > [href='/courses/web-development/'] > .categoryText",
    "DataBase_CloudComputing": "#courseExploreDropdown > [href='/courses/database-and-cloud-computing/'] > .categoryText",
    "SoftwareTesting" : "#courseExploreDropdown > [href='/courses/software-testing-and-automation/'] > .categoryText",
    "IT_Software" : "#courseExploreDropdown > [href='/courses/it-and-software/'] > .categoryText",
    "Network_Security" : "#courseExploreDropdown > [href='/courses/network-and-security/'] > .categoryText",
    "Web_3" : "#courseExploreDropdown > [href='/courses/web-3-0/'] > .categoryText",
    "MobileDevelopment" : "#courseExploreDropdown > [href='/courses/mobile-development/'] > .categoryText",
    "UI_UX" : "#courseExploreDropdown > [href='/courses/ui-ux-design/'] > .categoryText",
    "DigitalMarketing" : "#courseExploreDropdown > [href='/courses/digital-marketing/'] > .categoryText",
    "PremiumLibrary" : ".col-lg-5 > [href='/category/?library=premiumLibrary'] > .categoryText",
    "AtomicLibrary" : ".col-lg-5 > [href='/category/?library=atomicLibrary'] > .categoryText",
    "EssentialLibrary" : ".col-lg-5 > [href='/category/?library=essentialLibrary'] > .categoryText",
    "freelibrary" : ".col-lg-5 > [href='/category/?library=freeLibrary'] > .categoryText",
    "AllCourses" : ".col-lg-5 > [href='/category/'] > .categoryText",
    "CourseLibraries" : "[class='col-lg-5 col-md-5 col-xs-12'] > .ml-4",
    "SkillUpPopup" : "#NC_background_color",
    "SkillUpClose" : "#NC_CLOSE_ICON",
    "EntirePageBodyClass" : "[class='course-mainhead']",
    "YoutubePopup" : "[class='modal-content'] > #content",
    "ProfileName" : "[class='col-md-9 pl-2'] >h6",
    "ProfileEmail" : "[class='email-wrap text-secondary']",
    "ProfileCClass" : "[class='dropdown-item text-secondary mt-2']",
    "ProfileUserName" : "#user-name",
    "profile_email" : "[class='col-lg-6 col-xs-12'] > h5",
    "changePasswordTitle" : ".col > h1",
    "oldPasswordlabel" : "[for='oldPasswordInput']",
    "oldPasswordInput" : "#oldPasswordInput",
    "NewPasswordlabel" : "[for='newPasswordInput']",
    "NewPasswordInput" : "#newPasswordInput",
    "confirmPasswordlabel" : "[for='confirmPasswordInput']",
    "confirmPasswordInput" : "#confirmPasswordInput",
    "confirmButton" : "#change_btn",
    "PasswordConfirmMsg" : "#warn"
    

}