export const home={
    "subscribe" : "#subscribeNowButton",
    "gender" :  "#gender",
    "country" : "#country-selectized",
    "state" : "#state-selectized",
    "city" : "#city-selectized",
    "continue" :  "#continue-btn",
    "degree" : "#degree",
    "department" : "#department",
    "profile" : "#currentProfile",
    "company" : "#company",
    "role" : "#role",
    "location" : "#location",
    "experience" : "#experience",
    "skills" : "#skills-selectized",
    "codingProfile" : "#codingProfile",
    "reference" : "#refernce",
    "Interest" : "#interestedArea-selectized",
    "popup" : "[class='modal-content card-mod']",
    "GuviLogo" : ".navbar-brand",
    "FaQ" : "[href='/faq/']",
    "GeekPoints" : ".experience",
    "Rank" : ".rank",
    "FaQMessage" : ".cp-title",
    "ProfileAvatar" : ".gravatar-wrap",
    "CourseBanner" : "#CourseBannerView",
    "GuviLogo2" : "[alt='logo']",
    "CourseDetails" : "[class='iE sD']",
    "CourseNav" : ".icons-courses",
    "CourseTitle" : ".mr-auto",
    "Codekata" : ".icons-code-kata",
    "codekataPageText" : ".page-header",
    "webkata" : ".icons-Webkata",
    "webkataPageText" : ".page-header > .row",
    "Debugging" : ".icons-debugging",
    "DeubggingPageText" : ".page-header > .row",
    "IdePopUp" : "#tryButton",
    "Ide" : ".icons-ide",
    "editor" : "#editor",
    "LeaderBoard" : ".icons-leader-board",
    "Rewards" : ".icons-rewards",
    "RewardsPageText" : ".mb-3",
    "Referral" : ".icons-Referral",
    "ReferralpageText" : ".referal-heading-2",
    "Forum" : ".icons-forum",
    "AtomicLibraryMessage" : "[class='d-none d-md-block']",
    "AtomicLibraryParent" : "#atomicLib",
    "AtomicCourses" : "[class='course-tag atomic']",
    "AtomicFreeCourse" : ".freeCourseCustom",
    "EssentialLibraryParent" : "#essentialLib",
    "EssentialCourses" : "[class='course-tag essential']",
    "EssentialFreeCourse" : ".freeCourseCustom"

}