export const Reg ={
    "Logo" : "[class='welcome hidden-small-screen']",
    "image": "[alt='GUVI registration']",
    "singup": ".python-signup-btn > .nav-link",
    "googlesignup":'#google-button',
    "Firstnamelable":"[for='firstName']",
    "Firstname" :"#firstName",
    "NameForCertificate":".text-success > p",
    "Lastnamelabel" : "[for='lastName']",
    "Lastname" :"#lastName",
    "EmailLabel":"[for='emailInput']",
    "Email" :"#emailInput",
    "PasswordLabel" : "[for='passwordInput']",
    "Password" :"[id='passwordInput']",
    "PasswordToggle":"#togglePassword",
    "PasswordExtension" : "[class='label-grey password-cond']",
    "Passwordmin_char" : ".min-char",
    "Passwordone_num" : ".one-num",
    "Passwordone_alpha" : ".one-alpha",
    "MobileNoLabel" : "[for='mobileNumberInput']",
    "MobileNo" :"#mobileNumberInput",
    "Signup" :"#signup",
    "FirstNameErrorMessage":'form > :nth-child(1) > .invalid-feedback',
    "LastNameErrorMessage": 'form > :nth-child(2) > .invalid-feedback',
    "EmailErrorMessage" : '#emailgroup > .invalid-feedback',
    "ExistingEmailErrorMessage" :'#emailgroup > .invalid-feedback',
    "PasswordErrorMessage" : '.invalid-feedback > span',
    "MobileNoErrorMessage" : ':nth-child(5) > .invalid-feedback',
    "RegistrationSuccessMsg" : '#status_title',
    "RegistrationSuccessMsg2" :'#status_message',
    "RegistrationSuccessMsg3" :'#status_proceed',
    "LoginButton" : ".secondary-link",
    "loginlinkButton" : ".secondary-link > a"
}
